export const fifaTeams = [
  // CONMEBOL (10)
  { name: 'Argentina', confederation: 'CONMEBOL', logoUrl: 'https://upload.wikimedia.org/wikipedia/pt/7/7b/Asociaci%C3%B3n_del_F%C3%BAtbol_Argentino.svg' },
  { name: 'Bolívia', confederation: 'CONMEBOL', logoUrl: 'https://upload.wikimedia.org/wikipedia/pt/thumb/d/d4/Logotipo_da_Federa%C3%A7%C3%A3o_Boliviana_de_Futebol.svg/1200px-Logotipo_da_Federa%C3%A7%C3%A3o_Boliviana_de_Futebol.svg.png' },
  { name: 'Brasil', confederation: 'CONMEBOL', logoUrl: 'https://upload.wikimedia.org/wikipedia/pt/2/2b/Confedera%C3%A7%C3%A3o_Brasileira_de_Futebol_2019.svg' },
  { name: 'Chile', confederation: 'CONMEBOL', logoUrl: 'https://upload.wikimedia.org/wikipedia/pt/4/4c/Federa%C3%A7%C3%A3o_de_Futebol_do_Chile.svg' },
  { name: 'Colômbia', confederation: 'CONMEBOL', logoUrl: 'https://upload.wikimedia.org/wikipedia/pt/3/30/Federa%C3%A7%C3%A3o_Colombiana_de_Futebol.svg' },
  { name: 'Equador', confederation: 'CONMEBOL', logoUrl: 'https://upload.wikimedia.org/wikipedia/pt/2/27/Federaci%C3%B3n_Ecuatoriana_de_F%C3%BAtbol_logo.svg' },
  { name: 'Paraguai', confederation: 'CONMEBOL', logoUrl: 'https://upload.wikimedia.org/wikipedia/pt/5/52/Asociaci%C3%B3n_Paraguaya_de_F%C3%BAtbol.svg' },
  { name: 'Peru', confederation: 'CONMEBOL', logoUrl: 'https://upload.wikimedia.org/wikipedia/pt/9/91/Federaci%C3%B3n_Peruana_de_F%C3%BAtbol.svg' },
  { name: 'Uruguai', confederation: 'CONMEBOL', logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/df/Uruguay_football_association.svg' },
  { name: 'Venezuela', confederation: 'CONMEBOL', logoUrl: 'https://upload.wikimedia.org/wikipedia/pt/a/a2/Federaci%C3%B3n_Venezolana_de_F%C3%BAtbol_logo.svg' },

  // UEFA (55 - Selecionados os principais + outros, vamos colocar todos)
  { name: 'Albânia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e0/Albanian_Football_Association_logo.svg' },
  { name: 'Alemanha', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/pt/thumb/e/e3/Deutscher_Fu%C3%9Fball-Bund_logo.svg/1200px-Deutscher_Fu%C3%9Fball-Bund_logo.svg.png' },
  { name: 'Andorra', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/24/Andorran_Football_Federation_logo.svg' },
  { name: 'Armênia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/1/18/Football_Federation_of_Armenia_logo.svg' },
  { name: 'Áustria', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7b/%C3%96FB_Logo.svg' },
  { name: 'Azerbaijão', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/3/36/Association_of_Football_Federations_of_Azerbaijan_logo.svg' },
  { name: 'Bélgica', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/9/96/Royal_Belgian_Football_Association_logo.svg' },
  { name: 'Bielorrússia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/3/32/Football_Federation_of_Belarus_logo.svg' },
  { name: 'Bósnia e Herzegovina', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/8/87/Football_Association_of_Bosnia_and_Herzegovina_logo.svg' },
  { name: 'Bulgária', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/23/Bulgarian_Football_Union_logo.svg' },
  { name: 'Cazaquistão', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/8/87/Kazakhstan_Football_Federation_logo.svg' },
  { name: 'Chipre', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/1/15/Cyprus_Football_Association_logo.svg' },
  { name: 'Croácia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/6/60/Croatian_Football_Federation_logo.svg' },
  { name: 'Dinamarca', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c5/Danish_Football_Union_logo.svg' },
  { name: 'Escócia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c2/Scottish_Football_Association_logo.svg' },
  { name: 'Eslováquia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/0/07/Slovak_Football_Association_logo.svg' },
  { name: 'Eslovênia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/9/9c/Football_Association_of_Slovenia_logo.svg' },
  { name: 'Espanha', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/pt/3/30/Escudo_da_Sele%C3%A7%C3%A3o_Espanhola_de_Futebol.svg' },
  { name: 'Estônia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/0/06/Estonian_Football_Association_logo.svg' },
  { name: 'Finlândia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7b/Football_Association_of_Finland_logo.svg' },
  { name: 'França', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/pt/4/4e/F%C3%A9d%C3%A9ration_Fran%C3%A7aise_de_Football.svg' },
  { name: 'Geórgia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/22/Georgian_Football_Federation_logo.svg' },
  { name: 'Gibraltar', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/21/Gibraltar_Football_Association_logo.svg' },
  { name: 'Grécia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/0/02/Hellenic_Football_Federation_logo.svg' },
  { name: 'Holanda', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/pt/c/c1/Royal_Dutch_Football_Association_logo.svg' },
  { name: 'Hungria', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b3/Hungarian_Football_Federation_logo.svg' },
  { name: 'Ilhas Faroe', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4e/Faroe_Islands_Football_Association_logo.svg' },
  { name: 'Inglaterra', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/pt/thumb/d/d3/The_Football_Association_crest.svg/1200px-The_Football_Association_crest.svg.png' },
  { name: 'Irlanda', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6c/Football_Association_of_Ireland_logo.svg' },
  { name: 'Irlanda do Norte', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/3/30/Irish_Football_Association_logo.svg' },
  { name: 'Islândia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/23/Football_Association_of_Iceland_logo.svg' },
  { name: 'Israel', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/8/87/Israel_Football_Association_logo.svg' },
  { name: 'Itália', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/pt/0/07/Federazione_Italiana_Giuoco_Calcio.svg' },
  { name: 'Kosovo', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c7/Football_Federation_of_Kosovo_logo.svg' },
  { name: 'Letônia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/6/68/Latvian_Football_Federation_logo.svg' },
  { name: 'Liechtenstein', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1b/Liechtenstein_Football_Association_logo.svg' },
  { name: 'Lituânia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/0/0c/Lithuanian_Football_Federation_logo.svg' },
  { name: 'Luxemburgo', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/0/05/Luxembourg_Football_Federation_logo.svg' },
  { name: 'Macedônia do Norte', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Football_Federation_of_Macedonia_logo.svg' },
  { name: 'Malta', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b5/Malta_Football_Association_logo.svg' },
  { name: 'Moldávia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/1/14/Moldovan_Football_Federation_logo.svg' },
  { name: 'Montenegro', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/1/12/Football_Association_of_Montenegro_logo.svg' },
  { name: 'Noruega', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/24/Norwegian_Football_Federation_logo.svg' },
  { name: 'País de Gales', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/9/91/Football_Association_of_Wales_logo.svg' },
  { name: 'Polônia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4e/Polish_Football_Association_logo.svg' },
  { name: 'Portugal', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/pt/f/f3/FPF_logo_2014.svg' },
  { name: 'República Tcheca', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/25/Football_Association_of_the_Czech_Republic_logo.svg' },
  { name: 'Romênia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/e/eb/Romanian_Football_Federation_logo.svg' },
  { name: 'Rússia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/a/ab/Russian_Football_Union_logo.svg' },
  { name: 'San Marino', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/8/87/San_Marino_Football_Federation_logo.svg' },
  { name: 'Sérvia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/8/85/Football_Association_of_Serbia_logo.svg' },
  { name: 'Suécia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/0/00/Swedish_Football_Association_logo.svg' },
  { name: 'Suíça', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/5/53/Swiss_Football_Association_logo.svg' },
  { name: 'Turquia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/a/ab/Turkish_Football_Federation_logo.svg' },
  { name: 'Ucrânia', confederation: 'UEFA', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Ukrainian_Association_of_Football_logo.svg' },

  // CONCACAF (Alguns)
  { name: 'Estados Unidos', confederation: 'CONCACAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/18/US_Soccer_Logo.svg' },
  { name: 'México', confederation: 'CONCACAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/pt/5/53/Selecci%C3%B3n_de_f%C3%BAtbol_de_M%C3%A9xico.svg' },
  { name: 'Canadá', confederation: 'CONCACAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/8/82/Canadian_Soccer_Association_logo.svg' },
  { name: 'Costa Rica', confederation: 'CONCACAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e0/Costa_Rican_Football_Federation_logo.svg' },
  { name: 'Panamá', confederation: 'CONCACAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/5/5b/Panamanian_Football_Federation_logo.svg' },
  { name: 'Honduras', confederation: 'CONCACAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/6/64/National_Autonomous_Federation_of_Football_of_Honduras_logo.svg' },
  { name: 'Jamaica', confederation: 'CONCACAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/9/9f/Jamaica_Football_Federation_logo.svg' },
  { name: 'El Salvador', confederation: 'CONCACAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/9/91/Salvadoran_Football_Federation_logo.svg' },
  { name: 'Guatemala', confederation: 'CONCACAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/5/5b/National_Football_Federation_of_Guatemala_logo.svg' },
  { name: 'Haiti', confederation: 'CONCACAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d4/Haitian_Football_Federation_logo.svg' },

  // CAF (Alguns)
  { name: 'Egito', confederation: 'CAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c5/Egyptian_Football_Association_logo.svg' },
  { name: 'Senegal', confederation: 'CAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/pt/8/87/F%C3%A9d%C3%A9ration_S%C3%A9n%C3%A9galaise_de_Football.svg' },
  { name: 'Camarões', confederation: 'CAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6e/Cameroonian_Football_Federation_logo.svg' },
  { name: 'Marrocos', confederation: 'CAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/23/Royal_Moroccan_Football_Federation_logo.svg' },
  { name: 'Gana', confederation: 'CAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/9/93/Ghana_Football_Association_logo.svg' },
  { name: 'Argélia', confederation: 'CAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6a/Algerian_Football_Federation_logo.svg' },
  { name: 'Costa do Marfim', confederation: 'CAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/2b/Ivorian_Football_Federation_logo.svg' },
  { name: 'Nigéria', confederation: 'CAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4e/Nigeria_Football_Federation_logo.svg' },
  { name: 'Tunísia', confederation: 'CAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7b/Tunisian_Football_Federation_logo.svg' },
  { name: 'África do Sul', confederation: 'CAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a2/South_African_Football_Association_logo.svg' },
  { name: 'Mali', confederation: 'CAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4e/Malian_Football_Federation_logo.svg' },
  { name: 'Burkina Faso', confederation: 'CAF', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/3/30/Burkinab%C3%A9_Football_Federation_logo.svg' },
  
  // AFC (Alguns)
  { name: 'Japão', confederation: 'AFC', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/e/e4/Japan_national_football_team_crest.svg' },
  { name: 'Coreia do Sul', confederation: 'AFC', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a2/Korea_Football_Association_logo.svg' },
  { name: 'Arábia Saudita', confederation: 'AFC', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/9/91/Saudi_Arabian_Football_Federation_logo.svg' },
  { name: 'Austrália', confederation: 'AFC', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c5/Football_Australia_logo.svg' },
  { name: 'Irã', confederation: 'AFC', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/23/Football_Federation_Islamic_Republic_of_Iran_logo.svg' },
  { name: 'Catar', confederation: 'AFC', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1a/Qatar_Football_Association_logo.svg' },
  { name: 'China', confederation: 'AFC', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/2/2b/Chinese_Football_Association_logo.svg' },
  { name: 'Emirados Árabes Unidos', confederation: 'AFC', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/3/3b/United_Arab_Emirates_Football_Association_logo.svg' },
  { name: 'Síria', confederation: 'AFC', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/8/87/Syrian_Arab_Federation_for_Football_logo.svg' },
  { name: 'Iraque', confederation: 'AFC', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/0/07/Iraq_Football_Association_logo.svg' },

  // OFC (Alguns)
  { name: 'Nova Zelândia', confederation: 'OFC', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/b/b3/New_Zealand_Football_logo.svg' },
  { name: 'Fiji', confederation: 'OFC', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4e/Fiji_Football_Association_logo.svg' },
  { name: 'Ilhas Salomão', confederation: 'OFC', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7b/Solomon_Islands_Football_Federation_logo.svg' },
  { name: 'Taiti', confederation: 'OFC', logoUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1c/Tahitian_Football_Federation_logo.svg' }
];
